### ISSUE TITLE
Unstable behavior of xterm.js

### ISSUE THREAD

**Issue by todpole3** [TellinaTool/tellina_task_interface#2]
The following issues were observed with both the 'bento/ubuntu_16.04' box and the 'precise64' box.

1. Typing too fast always causes the task platform to freeze, i.e. xterm and the container stopped exchanging messages.

2. Sometimes the communication problem happens before I start to type anything, i.e. it cannot display the machine name and the "$". Screenshot attached:

![screen shot 2016-12-18 at 12 05 05 am](https://cloud.githubusercontent.com/assets/4227871/21292351/f09ac3de-c4b6-11e6-9c0b-7195b475fcdd.png)

3. A proportion of the time when it cannot display the machine name and the "$", it also cannot display the characters I typed, but I can observe that when I'm typing, xterm and the container are exchanging messages. Screenshot attached:

![screen shot 2016-12-18 at 12 06 51 am](https://cloud.githubusercontent.com/assets/4227871/21292372/b0bc4534-c4b7-11e6-8e01-1f1f791e38cd.png)

4. The rest of the time when it cannot display the machine name and the "$", it can display the characters I typed. Screenshot attached:

![screen shot 2016-12-17 at 11 43 49 pm](https://cloud.githubusercontent.com/assets/4227871/21292386/1540744e-c4b8-11e6-9038-0c6e110eaa99.png)

2, 3, 4 happen non-deterministically, not always. I'm not sure if such random behavior can lead to the conclusion that there exists issue with xterm.js or its interface with the other modules, besides the problems with the Django channel that we suspect.

**Comment by kvu787** [comment]
I've refactored WebSocket functionality out of Django into a Node.js proxy server: https://github.com/TellinaTool/tellina_task_interface/tree/websocket_refactor. I've tested a single user using the task interface and there are no performance issues.

**Comment by todpole3** [comment]
The refactoring works fine for me. Thanks @kvu787
