### ISSUE TITLE
Permission Denied Error when manipulating the file system

### ISSUE THREAD

**Issue by todpole3** [TellinaTool/tellina_task_interface#6]
I added the following line to change the initial file permission of our task systems for the current implementation reports `permission denied` when the user tries to creates a file in a pre-generated folder. https://github.com/TellinaTool/tellina_task_interface/blob/precise64_box/website/models.py#L138

![screen shot 2016-12-27 at 11 06 04 pm](https://cloud.githubusercontent.com/assets/4227871/21515983/1cc8a08c-cc89-11e6-8bea-5ec906f34fe3.png)

I must have made mistakes s.t. the line doesn't achieve what's expected. While I suppose there would simply be an internal server error, xterm did something strange. It exposed the content of the entire `backend_container_image` directory.

**Comment by kvu787** [comment]
Closed via https://github.com/TellinaTool/tellina_task_interface/commit/2c4a4c8ca664cbdd6e959f4736b5908c618eb1b9.

I recommend that you use the same username for all backend containers, otherwise, you'll need to edit files in several places to create a different username per container. (See the files edited in the  commit.)

**Comment by todpole3** [comment]
@kvu787 Thanks a lot.

However, I'm still getting the `permission_denied` error.

It looks like the reason is that when python3 initializes the file system, it directly writes the virtual file system instead of the docker image, hence the "users" in the two environments do not match.
```
            dict_2_disk(json.loads(task.initial_filesystem),
                pathlib.Path('/{}/home'.format(container.filesystem_name)))

            # directory
            if not path.exists():
                path.mkdir()
            dict_2_disk(subtree, path)
```

**Comment by kvu787** [comment]
I'm pretty sure I ran into this same issue before. I resolved it by creating all files and directories in `dict_2_disk` with user=vagrant and group=vagrant. This functionality was dropped between these commits: https://github.com/TellinaTool/tellina_task_interface/commit/c2842e8c01c8bffadd35e00b1d4e4d166c790a7e#diff-7ad50190f57320f6ef0ac170bb521d2eL32.

@todpole3  Can you resolve https://github.com/TellinaTool/tellina_task_interface/issues/7 so I can investigate + fix this?

**Comment by kvu787** [comment]
There are 2 sets of permissions:

1. Permissions on the virtual file system mounted on the host (`vagrant@precise64`): `/a-b-study_session-1/home`
2. Permissions on the file system within the Docker container (`study_participant@e3e5edcf9d6e`): `/home/study_participant`

For [1], the group and owner can be anything. (So what I said in https://github.com/TellinaTool/tellina_task_interface/issues/6#issuecomment-269753606 is incorrect.)
For [2], the group and owner must be `study_participant`.

**Comment by todpole3** [comment]
@kvu787 The issue is solved. Thanks very much.

We might want to switch to a shorter universal name, so far it seems to be taking too much space.

<img width="629" alt="screen shot 2016-12-30 at 11 56 09 pm" src="https://cloud.githubusercontent.com/assets/4227871/21576622/c845f176-ceeb-11e6-92a1-2d791cd2a718.png">
