### ISSUE TITLE
Terminal displays at most 24 rows

### ISSUE THREAD

**Issue by todpole3** [TellinaTool/tellina_task_interface#9]
I've tried using the add on `fit.js` and set up the `rows` variable manually. Couldn't get the terminal display to fit the entire div.

![screen shot 2016-12-31 at 3 14 22 pm](https://cloud.githubusercontent.com/assets/4227871/21579547/fbb1ea44-cf6b-11e6-8378-757a50f174ca.png)

**Comment by kvu787** [comment]
I recommend trying to achieve this with the xterm.js demo (https://github.com/sourcelair/xterm.js/tree/master/demo), and then implementing it in the task interface.

**Comment by todpole3** [comment]
Fixed by explicitly set terminal container height to 96%.
